Info:
  Era: 2016_postVFP
  Channel: EMU

Z:
  MassCut: 200

Muon:
  Pt: 52
  Eta: 2.4
  ID: global
  ISOinverted: false
  ISO: 0.1
  doMCSmearing: true
  MCSmearing:
    barrel:
      smearing: -1
      sigma: 0.0102 + 6.77e-5 * x -3.72e-8 * x^2 + 8.53e-12 * x^3
    endcap:
      smearing: -1
      sigma: 0.0129 + 6.48e-5 * x -3.04e-8 * x^2 + 6.63e-12 * x^3

Electron:
  Pt: 20
  Eta: 2.5
  IDinverted: false

Pair:
  Charge: same

Jet:
  Pt: 30
  Eta: 2.4
  ID: 6
  PUID: 1
  BTag: M
  Cleaning: false

Correction:
  Reco: true
  ID: true
  ISO: true
  Trigger: true
  ElecReco: true
  ElecID: true
  ElecMisCharge: false
  PileUp: true
  L1PreFiring: true
  JetPU: true
  BTag: true
  TopPtReweighing: true

Efficiency:
  Reco:
    Path: ../../EfficiencyTable/muon/high/ScaleFactors_Muon_highPt_RECO_2016_schemaV2.json
    Name: NUM_GlobalMuons_DEN_TrackerMuonProbes
  ID:
    Path: ../../EfficiencyTable/muon/high/ScaleFactors_Muon_highPt_IDISO_2016_schemaV2.json
    Name: NUM_HighPtID_DEN_GlobalMuonProbes
  ISO:
    Path: ../../EfficiencyTable/muon/high/ScaleFactors_Muon_highPt_IDISO_2016_schemaV2.json
    Name: NUM_probe_LooseRelTkIso_DEN_HighPtProbes
  Trigger:
    Path: ../../correctionlib/muon/high/2016_postVFP/ScaleFactors_Muon_highPt_HLT_2016_schemaV2.json
    Name: NUM_HLT_DEN_HighPtLooseRelIsoProbes
  ElecReco:
    Path: ../../correctionlib/electron/reco/EGM_2016postVFP.json
    Name: UL-Electron-ID-SF
  ElecID:
    Path: ../../correctionlib/electron/Run2UL_ID.json
    Name: UL-Electron-ID-SF
  ElecMisCharge:
    Path: ../../EfficiencyTable/elec/ChargeMisId/CFRate2016b.root
  JetPU:
    Path: ../../correctionlib/JetPUID/2016postVFP.json
  BTag:
    Path: ../../correctionlib/bTag/2016postVFP.json
  BTagEff:
    bQuark: ../../EfficiencyTable/BTagEff/DY_2016_postVFP_h_BTagEff_B.txt
    cQuark: ../../EfficiencyTable/BTagEff/DY_2016_postVFP_h_BTagEff_C.txt
    lQuark: ../../EfficiencyTable/BTagEff/DY_2016_postVFP_h_BTagEff_L.txt

Pileup:
  Data: PileupHistogram-goldenJSON-13tev-2016-postVFP-69200ub-99bins.root
  MC: MC_2016.root
