Z:
  MassCut: 200

Electron:
  LeadingPt: 50
  SubLeadingPt: 20
  Eta: 2.4
  ID: 3
  Charge: opposite


Jet:
  Pt: 30
  Eta: 2.4
  ID: 6
  PUID: 4
  BTag: 0.2783
  Cleaning: false

Correction:
  Reco: false
  ID: false
  ISO: false
  Trigger: false
  PileUp: false
  L1PreFiring: false
  JetPU: false
  BTag: false

Efficiency:
  Reco:
    Path: ../../xxx.json
    Name: XXX
  ID:
    Path: ../../xxx.json
    Name: XXX
  ISO:
    Path: ../../xxx.json
    Name: XXX
  Trigger:
    Path: ../../xxx.json
    Name: XXX
  JetPU:
    Path: ../../xxx.csv
  BTag:
    Path: ../../xxx.csv
  BTagEff:
    bQuark: ../../xxx.txt
    cQuark: ../../xxx.txt
    lQuark: ../../xxx.txt

Pileup:
  Data: PileupHistogram-goldenJSON-13tev-2018-69200ub-99bins.root
  MC: MC_2018.root
