Info:
  Era: 2016_postVFP
  Channel: EE

Z:
  MassCut: 200

Electron:
  LeadingPt: 50
  SubLeadingPt: 20
  Eta: 2.4
  ID: 3
  Charge: opposite

Jet:
  Pt: 30
  Eta: 2.4
  ID: 6
  PUID: 4
  BTag: 0.2489
  Cleaning: false

Correction:
  Reco: false
  ID: false
  ISO: false
  Trigger: false
  PileUp: false
  L1PreFiring: false
  JetPU: false
  BTag: false

Efficiency:
  Reco:
    Path: ../../EfficiencyTable/muon/high/ScaleFactors_Muon_highPt_RECO_2016_schemaV2.json
    Name: NUM_GlobalMuons_DEN_TrackerMuonProbes
  ID:
    Path: ../../EfficiencyTable/muon/high/ScaleFactors_Muon_highPt_IDISO_2016_schemaV2.json
    Name: NUM_HighPtID_DEN_GlobalMuonProbes
  ISO:
    Path: ../../EfficiencyTable/muon/high/ScaleFactors_Muon_highPt_IDISO_2016_schemaV2.json
    Name: NUM_probe_LooseRelTkIso_DEN_HighPtProbes
  Trigger:
    Path: ../../correctionlib/muon/medium/2016_postVFP.json
    Name: NUM_Mu50_or_TkMu50_DEN_CutBasedIdGlobalHighPt_and_TkIsoLoose
  JetPU:
    Path: ../../EfficiencyTable/JetPUID/2016_L.csv
  BTag:
    Path: ../../EfficiencyTable/BTag/wp_deepJet_2016postVFP.csv
  BTagEff:
    bQuark: ../../EfficiencyTable/BTagEff/DY_2016_postVFP_h_BTagEff_B.txt
    cQuark: ../../EfficiencyTable/BTagEff/DY_2016_postVFP_h_BTagEff_C.txt
    lQuark: ../../EfficiencyTable/BTagEff/DY_2016_postVFP_h_BTagEff_L.txt

Pileup:
  Data: PileupHistogram-goldenJSON-13tev-2016-postVFP-69200ub-99bins.root
  MC: MC_2016.root
