Info:
  Era: 2018
  Channel: EMU

Z:
  MassCut: 200

Muon:
  Pt: 52
  Eta: 2.4
  ID: global
  ISO: 0.1
  doMCSmearing: true
  MCSmearing:
    barrel:
      smearing: -1
      sigma: 0.0108 + 5.93e-5 * x -3.08e-8 * x^2 + 6.04e-12 * x^3
    endcap:
      smearing: 0.46
      sigma: 0.0136 + 5.47e-5 * x -2.3e-8 * x^2 + 4.66e-12 * x^3

Electron:
  Pt: 50
  Eta: 2.5
  ID: 3

Jet:
  Pt: 30
  Eta: 2.5
  ID: 6
  PUID: 4
  BTag: M
  Cleaning: false

Correction:
  Reco: true
  ID: true
  ISO: true
  Trigger: true
  ElecReco: true
  ElecID: true
  PileUp: true
  L1PreFiring: true
  JetPU: true
  BTag: true
  TopPtReweighing: true

Efficiency:
  Reco:
    Path: ../../correctionlib/muon/high/ScaleFactors_Muon_highPt_RECO_2018_schemaV2.json
    Name: NUM_GlobalMuons_DEN_TrackerMuonProbes
  ID:
    Path: ../../correctionlib/muon/high/ScaleFactors_Muon_highPt_IDISO_2018_schemaV2.json
    Name: NUM_HighPtID_DEN_GlobalMuonProbes
  ISO:
    Path: ../../correctionlib/muon/high/ScaleFactors_Muon_highPt_IDISO_2018_schemaV2.json
    Name: NUM_probe_LooseRelTkIso_DEN_HighPtProbes
  Trigger:
    Path: ../../correctionlib/muon/high/ScaleFactors_Muon_highPt_HLT_2018_schemaV2.json
    Data: NUM_HLT_DEN_HighPtLooseRelIsoProbes_DATAeff
    MC: NUM_HLT_DEN_HighPtLooseRelIsoProbes_MCeff
  ElecReco:
    Path: ../../correctionlib/electron/reco/EGM_2018.json
    Name: UL-Electron-ID-SF
  ElecID:
    Path: ../../correctionlib/electron/reco/EGM_2018.json
    Name: UL-Electron-ID-SF
  ElecMisCharge:
    Path: ../../EfficiencyTable/elec/ChargeMisId/CFRate2018.root
  JetPU:
    Path: ../../correctionlib/JetPUID/2018.json
  BTag:
    Path: ../../correctionlib/bTag/2018.json
  BTagEff:
    Path: ../../correctionlib/bTag/eff/BTagEff_MUMU_eff_AbsEta_PtMerged.json

Pileup:
  Data: PileupHistogram-goldenJSON-13tev-2018-69200ub-99bins.root
  MC: MC_2018.root
