Z:
  MassCut: 10

Muon:
  LeadingMuonPt: 26
  SubLeadingMuonPt: 10
  Eta: 2.4
  ID: TightID
  ISO: TightPFRelIso
  Charge: opposite

Electron:
  Pt: 10
  Eta: 2.4
  SCEtaVeto: true
  ID: TightID

Jet:
  Pt: 30
  Eta: 2.4
  ID: Loose
  BTag: 0.5426
  Cleaning: true

Trigger:
  IsoMu24

Switch:
  ID: false
  ISO: false
  Trigger: false
  PileUp: false
  L1PreFiring: false

Efficiency:
  ID: Run2018_UL_ID.txt
  ISO: Run2018_UL_ISO.txt
  Trigger_data: Run2018_UL_TRIG_DATAeff.txt
  Trigger_MC: Run2018_UL_TRIG_MCeff.txt

Pileup:
  Data: PileupHistogram-goldenJSON-13tev-2018-69200ub-99bins.root
  MC: MC_2018.root

