Info:
  Era: 2017
  Channel: EMU

Z:
  MassCut: 200

Muon:
  Pt: 52
  Eta: 2.4
  ID: global
  ISOinverted: true
  ISO: 0.1
  doMCSmearing: true
  MCSmearing:
    barrel:
      smearing: -1
      sigma: 0.0104 +6.11e-5 * x -3.31e-8 * x^2 + 6.73e-12 * x^3
    endcap:
      smearing: 0.3202
      sigma: 0.0121 + 5.92e-5 * x -2.61e-8 * x^2 + 5.11e-12 * x^3

Electron:
  Pt: 50
  Eta: 2.5
  ID: 3
  IDinverted: true

Pair:
  Charge: opposite

Jet:
  Pt: 30
  Eta: 2.5
  ID: 6
  PUID: 4
  BTag: M
  Cleaning: false

Correction:
  Reco: true
  ID: true
  ISO: true
  Trigger: true
  ElecReco: true
  ElecID: true
  ElecMisCharge: false
  PileUp: true
  L1PreFiring: true
  JetPU: true
  BTag: true
  TopPtReweighing: true

Efficiency:
  Reco:
    Path: ../../correctionlib/muon/high/ScaleFactors_Muon_highPt_RECO_2017_schemaV2.json
    Name: NUM_GlobalMuons_DEN_TrackerMuonProbes
  ID:
    Path: ../../correctionlib/muon/high/ScaleFactors_Muon_highPt_IDISO_2017_schemaV2.json
    Name: NUM_HighPtID_DEN_GlobalMuonProbes
  ISO:
    Path: ../../correctionlib/muon/high/ScaleFactors_Muon_highPt_IDISO_2017_schemaV2.json
    Name: NUM_probe_LooseRelTkIso_DEN_HighPtProbes
  Trigger:
    Path: ../../correctionlib/muon/high/ScaleFactors_Muon_highPt_HLT_2017_schemaV2.json
    Data: NUM_HLT_DEN_HighPtLooseRelIsoProbes_DATAeff
    MC: NUM_HLT_DEN_HighPtLooseRelIsoProbes_MCeff
  ElecReco:
    Path: ../../correctionlib/electron/reco/EGM_2017.json
    Name: UL-Electron-ID-SF
  ElecID:
    Path: ../../correctionlib/electron/reco/EGM_2017.json
    Name: UL-Electron-ID-SF
  ElecMisCharge:
    Path: ../../EfficiencyTable/elec/ChargeMisId/CFRate2017.root
  JetPU:
    Path: ../../correctionlib/JetPUID/2017.json
  BTag:
    Path: ../../correctionlib/bTag/2017.json
  BTagEff:
    Path: ../../correctionlib/bTag/eff/BTagEff_MUMU.json

Pileup:
  Data: PileupHistogram-goldenJSON-13tev-2017-69200ub-99bins.root
  MC: MC_2017.root
